name: Football Post Automation

on:
  schedule:
    # רץ ביום שלישי (אמצע שבוע) וביום שבת (סוף שבוע) בשעה 10:00 בבוקר
    - cron: '0 10 * * 2,6'
  workflow_dispatch: # זה השורה שמאפשרת לך להריץ ידנית!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/set-up-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: python main.py
