name: Football Post Automation

on:
  schedule:
    # רץ ביום שלישי ושבת בשעה 10:00 בבוקר
    - cron: '0 10 * * 2,6'
  workflow_dispatch: # מאפשר הרצה ידנית

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pillow

      - name: Run script
        env:
          # כאן החיבור הקריטי: 
          # אנחנו אומרים ל-GitHub לקחת את הסוד שקראת לו RAPIDAPI_KEY
          # ולהכניס אותו למשתנה שהקוד שלך מחפש
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python main.py

      - name: Upload Post Images
        uses: actions/upload-artifact@v4
        with:
          name: soccer-posts
          path: "*.jpg"
